name: Update Schedule Data from Google Sheet

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs automatically every day at 5:00 UTC
  schedule:
    - cron: '0 5 * * *'

# This grants the Action permission to write files back to your repository
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code
      - name: Check out repo
        uses: actions/checkout@v3

      # Step 2: Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install the necessary Python libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run your Python script to generate all semester JSON files
      - name: Run script to convert Google Sheet to JSON
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        # Make sure this filename matches your Python script exactly
        run: python convert_excel.py

      # Step 5: Inject the current timestamp into your index.html
      - name: Inject Timestamp into HTML
        run: |
          TIMESTAMP=$(TZ="America/Denver" date +"%B %d, %Y at %I:%M %p %Z")
          sed -i 's|<span id="last-updated-timestamp">.*</span>|<span id="last-updated-timestamp">'"$TIMESTAMP"'</span>|' index.html

      # Step 6: Commit all generated files back to the repository
      - name: Commit and push if there are changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          # This command adds the updated index.html AND all .json files
          git add index.html *.json
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "Automated schedule data update"
            git push
          else
            echo "No changes to commit."
          fi
